name: school_management_system
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: "3.7.2"
dependencies:
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  custom_navigation_bar: ^0.8.2
  dio: ^5.8.0+1
  file_picker: ^10.1.7
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_downloader: ^1.12.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.1.0
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_zoom_drawer: ^3.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  rounded_loading_button: ^2.1.0
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/LOGO2.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: RedHatDisplay-Bold
      fonts:
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
    - family: RedHatDisplay-Light
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
    - family: RedHatDisplay-Medium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
    - family: RedHatDisplay-Regular
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
    # - family: SFProDisplay-Bold
    #   fonts:
    #     - asset: assets/fonts/SFProDisplay-Bold.OTF
    # - family: SFProDisplay-Medium
    #   fonts:
    #     - asset: assets/fonts/SFProDisplay-Medium.OTF
    # - family: SFProDisplay-Regular
    #   fonts:
    #     - asset: assets/fonts/SFProDisplay-Regular.OTF
